rss: Simplify entry formatting
jesopo/bitbot pull request #370
Opened 2023-06-13 17:40 UTC by progval

2023-06-13 19:42 UTC, examknow requested changes

2023-06-13 19:42 UTC, examknow commented on modules/rss.py
> +            template = string.Template(channel.get_setting("rss-format", "$longtitle: $title by $author - $link"))
I think it's probably best to use [`format_token_replace()`](https://github.com/bitbot-irc/bitbot/blob/develop/src/utils/parse/__init__.py#L133) here for the sake of consistency with other modules. I'm uncertain why it wasn't done this way when the feature was added.

2023-06-13 20:03 UTC, examknow requested changes

2023-06-13 20:03 UTC, examknow commented on modules/rss.py
> +        )
Let's merge the `variables` and `entry` dicts into one so we can just format them all as one.
```suggestion
        )
        variables.update(entry)
```

2023-06-13 20:03 UTC, examknow commented on modules/rss.py
> +            template = channel.get_setting("rss-format", "$longtitle: $title by $author - $link")
```suggestion
            template = channel.get_setting("rss-format", "${longtitle}: ${title} by ${author} - ${link}")
```

2023-06-13 20:03 UTC, examknow commented on modules/rss.py
> +            format = format_token_replace(template, variables).format(**entry)
`format_token_replace()` returns a tuple but we only care about the formatted string bit here. we also no longer need the `.format()` because we've merged the `entry` dict with the `variables` dict.
```suggestion
            _, format = utils.parse.format_token_replace(template, variables)
```

2023-06-13 20:03 UTC, examknow commented on modules/rss.py
> +            format = "{longtitle}: {title} by {author} - {link}".format(**variables)
This entire check is now unnecessary since `format_token_replace()` will silently fail to convert any unknown placeholders.

2023-06-13 20:07 UTC, progval commented on modules/rss.py
> +        )
This would change the behavior though. Let's keep this for another PR?

2023-06-13 20:07 UTC, progval commented on modules/rss.py
> +            template = channel.get_setting("rss-format", "$longtitle: $title by $author - $link")
that's also a breakage for existing configs, isn't it?

2023-06-13 20:09 UTC, examknow commented on modules/rss.py
> +            template = channel.get_setting("rss-format", "$longtitle: $title by $author - $link")
I don't think custom formatting really gets used tbh, but some way to detect/migrate it would be good

2023-06-13 20:11 UTC, examknow commented on modules/rss.py
> +        )
The problem with that is the current behavior kinda sucks. I'd prefer to not have all this fragmentation in our formatting logic.

2023-06-13 20:14 UTC, examknow commented on modules/rss.py
> +            template = channel.get_setting("rss-format", "$longtitle: $title by $author - $link")
Perhaps we could perform a sweep of the `rss-format` configs at module load time and convert `$variable` and `{variable}` to `${variable}` and then set a bot config value to note that the migration has happened. I can't think of a nicer way to do this without majorly overcomplicating things.

2023-06-14 00:21 UTC, examknow commented
The following should be sufficient for migration of old configs. Just place it inside the BaseModule subclass.

```python
import re

def _migrate_formats(self):
    count = 0
    migration_sub = re.compile(r"(?:\$|{)+(?P<variable>[^}\s]+)(?:})?")
    old_formats = self.bot.database.execute_fetchall("""
        SELECT channel_id, value FROM channel_settings
        WHERE setting = 'rss-format'
    """)

    for channel_id, format in old_formats:
        new_format = migration_re.sub(r"${\1}", format)
        self.bot.database.execute("""
            UPDATE channel_settings SET value = ?
            WHERE setting = 'rss-format'
            AND channel_id = ?
        """, [new_format, channel_id])
        count += 1

    self.log.info("Successfully migrated %d rss-format settings")

def on_load(self):
    if self.bot.get_setting("rss-fmt-migration", False):
        self.log.info("Attempting to migrate old rss-format settings")
        self._migrate_formats()
        self.bot.set_setting("rss-fmt-migration", True)
```

2023-06-14 02:12 UTC, examknow approved these changes
Tested and working

2023-06-14 02:12 UTC, merged